common/models/Comment.php
<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * Comment model
 *
 * @property int $id
 * @property int $user_id
 * @property int $advert_id
 * @property string $subject
 * @property string $content
 *
 * @property Advert $advert
 * @property User $user
 */
class Comment extends ActiveRecord
{
    public static function tableName(): string
    {
        return '{{%comment}}';
    }

    public function rules(): array
    {
        return [
            ['subject', 'string', 'max' => 255],
            ['content', 'string'],

            [['user_id', 'advert_id'], 'integer'],
            [['user_id', 'advert_id', 'subject', 'content'], 'required'],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'subject' => Yii::t('app', 'Tárgy'),
            'content' => Yii::t('app', 'Üzenet'),
        ];
    }

    public function getAdvert()
    {
        return $this->hasOne(Advert::class, ['id' => 'advert_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public static function findById(int $id): Comment
    {
        return static::findOne(['id' => $id]);
    }
}

common/models/CommentForm.php
<?php
namespace common\models;

use Yii;
use yii\base\Model;

/**
 * Comment form
 */
class CommentForm extends Model
{
    /** @var int */
    public $advertId;
    /** @var string */
    public $content;
    /** @var string */
    public $subject;
    /** @var int */
    public $userId;

    public function rules(): array
    {
        return [
            ['subject', 'string', 'max' => 255],
            ['content', 'string'],

            [['userId', 'advertId'], 'number'],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'advertId' => Yii::t('app', 'Hirdetés ID'),
            'content' => Yii::t('app', 'Üzenet'),
            'subject' => Yii::t('app', 'Tárgy'),
            'userId' => Yii::t('app', 'Felhasználó ID'),
        ];
    }

    public function fillTo(Comment $comment, int $advertId): Comment
    {
        $comment->advert_id = $advertId;
        $comment->content = $this->content;
        $comment->subject = $this->subject;
        $comment->user_id = Yii::$app->user->id;

        return $comment;
    }
}

frontend/controllers/CommentController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\Comment;
use common\models\CommentForm;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class CommentController
 */
class CommentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create', 'delete'],
                'rules' => [
                    [
                        'actions' => ['create', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionCreate()
    {
        $commentForm = new CommentForm();
        if ($commentForm->load(Yii::$app->request->post()) && $commentForm->validate()) {
            $comment = $commentForm->fillTo(new Comment(), (int)Yii::$app->request->post('advertId'));

            try {
                if (!$comment->save()) {
                    throw new Exception(
                        "Failed to save {$comment->subject} comment." . json_encode($comment->getErrors())
                    );
                }

                Yii::$app->session->setFlash('success', 'Sikeres megjegyzés létrehozás.');
            } catch(\Throwable $e) {
                Yii::error($e);
                Yii::$app->session->setFlash('danger', 'Sikertelen megjegyzés létrehozás.');
            }
        }

        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }

    public function actionDelete(int $id)
    {
        $comment = Comment::findById($id);

        try {
            if (empty($comment)) {
                throw new Exception("Failed to find #{$id} comment.");
            }

            $comment->delete();

            Yii::$app->session->setFlash('success', 'Sikeres megjegyzés törlés!');
        } catch (\Throwable $e) {
            Yii::error($e);
            Yii::$app->session->setFlash('danger', 'Sikertelen megjegyzés törlés!');
        }

        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }
}

frontend/views/comment/_create.php
<?php
/** @var CommentForm $commentForm */

use \common\models\CommentForm;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
?>
<div class="col-6 card-body align-self-center">
    <div class="text-center mt-2">
        <h5>Új megjegyzés</h5>
    </div>

    <?php $form = ActiveForm::begin([
        'action' => '/comment/create',
        'id' => 'form-comment',
        'method' => 'post',
        'enableClientValidation' => false,
    ]); ?>

    <?= $form->field($commentForm, 'subject')->textInput() ?>
    <?= $form->field($commentForm, 'content')->textarea(['rows' => 5]) ?>

    <?= $form->field($commentForm, 'advertId')
        ->hiddenInput(['name' => 'advertId', 'value' => Yii::$app->request->get('advertId')])
        ->label(false) ?>

    <div class="form-group text-center">
        <?= Html::submitButton('Küldés', ['class' => 'btn btn-primary', 'name' => 'comment-button']) ?>
    </div>

    <?php ActiveForm::end() ?>
</div>

frontend/views/comment/_delete.php
<?php
/** @var Comment $comment */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\Modal;

$buttons = Html::button('Törlés', [
    'type' => 'submit',
    'class' => 'btn btn-danger',
    'form' => 'comment-delete-form',
]);
$buttons .= Html::button('Mégse', [
    'type' => 'button',
    'class' => 'btn btn-outline-secondary',
    'data-dismiss' => 'modal'
]);

Modal::begin([
    'id' => 'modal',
    'footer' => $buttons,
    'footerOptions' => ['class' => 'justify-content-center'],
    'headerOptions' => ['id' => 'modalHeader'],
    'size' => 'modal-lg',
    'title' => 'Megjegyzés törlése',
]);
?>
<form action="<?= Url::to(['/comment/delete']) ?>" class="form-horizontal" id="comment-delete-form" method="get">
    <div class="text-center">
        <p>Biztosan törlöd a kiválasztott megjegyzésed?</p>
    </div>

    <?= Html::hiddenInput('id') ?>
</form>

<?php Modal::end(); ?>

frontend/views/comment/_view.php
<?php
/** @noinspection PhpUndefinedMethodInspection */

/** @var View $this */
/** @var Advert $advert */

use yii\helpers\Html;
use common\models\Comment;

$blockWidth = 'col-6';
if (Yii::$app->user->isGuest) {
    $blockWidth = 'col-12';
}
?>
<div class="<?= $blockWidth ?> border rounded overflow-auto" style="height: 500px;">
    <?php foreach ($advert->comments as $comment) { ?>
        <?php /** @var Comment $comment */?>
        <div class="row justify-content-start border rounded bg-light p-3">
            <div class="col-11">
                <div class="row">
                    <div class="col-12">
                        <b>
                            <?= $comment->subject ?>
                            <span class="badge badge-secondary ml-1"><?= $comment->user->email ?></span>
                        </b>
                    </div>

                    <div class="col-12 pt-3">
                        <p class="ml-3"><?= $comment->content ?></p>
                    </div>
                </div>
            </div>

            <?php if (Yii::$app->user->id === $advert->user_id) { ?>
                <div class="col-1 align-self-center">
                    <?= Html::button('<i></i>', [
                        'class' => 'far fa-trash-alt border-0 bg-light',
                        'data-target' => '#modal',
                        'data-toggle' => 'modal',
                        'data-id' => $comment->id,
                        'title' => 'Megjegyzés törlése',
                    ]); ?>

                    <?= $this->render('_delete') ?>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
</div>